### ISSUE TITLE
Question: Can the X1C3 be used without a battery?

### ISSUE THREAD

**Issue by ITCMD** [Mihara/x1c3tool#1]
Wondering if you are able to test if the X1C3 can be made to run directly off 5v with no power in. Want to use it in my car with no worry for charging it.

**Comment by Mihara** [comment]
That would mean removing the battery, which would involve disassembling it, so verifying will have to wait until I have a chance to do that.

**Comment by Mihara** [comment]
Sorry it took so long to get to that.

Yes, when the battery is completely disconnected, and power supplied to the USB, it powers on and otherwise works, which means you can keep it in your car forever with no issues.

**Comment by ITCMD** [comment]
> Sorry it took so long to get to that.
> 
> Yes, when the battery is completely disconnected, and power supplied to the USB, it powers on and otherwise works, which means you can keep it in your car forever with no issues.

No apologies needed. Thank you so much for checking that!
