### ISSUE TITLE
Windows fails to write config to device

### ISSUE THREAD

**Issue by crackedatom** [Mihara/x1c3tool#2]
Using x1c3tool to upload config back to the device appears to not actually make any changes. No errors are reported in the CLI and downloading works fine. Uploading and downloading work as expected on RPi 3b using the ARM version with the same config files.

Windows 10
x1c3tool v1.0.1

**Comment by Mihara** [comment]
Turns out, Nim streams behave *subtly differently* on Windows, and require flushing more thoroughly. Fixed!

It is a lucky coincidence that I just recently acquired a real Windows machine and could actually test this. :)
